
var questionsRank1 = [
    {"questionType":3,
    "qOrder": 1,
    "qText":"Right",
    "qImg":"img/right1.png",
    "answerType":0,
    "a1Img":"",
    "a1text":"",
    "a2Img":"",
    "a2text":"",
    "answer": 2,
    "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Right",
        "qImg":"img/left1.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/left1.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/right1.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5},

    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/right1.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/left1.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/left1.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/right1.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
];


var questionsRank2 = [
    {"questionType":3,
        "qOrder": 1,
        "qText":"Right",
        "qImg":"img/right2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Right",
        "qImg":"img/left2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/left2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/right2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Right",
        "qImg":"img/right3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Right",
        "qImg":"img/left3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/left3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/right3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Right",
        "qImg":"img/right4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Right",
        "qImg":"img/left4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/left4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 1,
        "qText":"Left",
        "qImg":"img/right4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/right2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/left2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/left2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/right2.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/right3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/left3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/left3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/right3.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/right4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Right",
        "qImg":"img/left4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 2,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/left4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
    ,
    {"questionType":3,
        "qOrder": 2,
        "qText":"Left",
        "qImg":"img/right4.png",
        "answerType":0,
        "a1Img":"",
        "a1text":"",
        "a2Img":"",
        "a2text":"",
        "answer": 1,
        "questionReward": 0.5}
];


var questionsRank3 = [
    {"questionType":1,
        "qOrder": 1,
        "qText":"1 + 1 = ",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"1",
        "a2Img":"",
        "a2text":"2",
        "answer": 2,
        "qId":1,
        "questionReward": 1
    }
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"17 + 86 = ",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"103",
        "a2Img":"",
        "a2text":"113",
        "answer": 1,
        "qId":2,
        "questionReward": 1}
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"1 * 1 * 1 - 1 = ",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"1",
        "a2Img":"",
        "a2text":"0",
        "answer": 2,
        "qId":3,
        "questionReward": 1}
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"8 + 9 = ",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"17",
        "a2Img":"",
        "a2text":"22",
        "answer": 1,
        "qId":4,
        "questionReward": 1}
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"Eeny, meeny, miny",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"moe",
        "a2Img":"",
        "a2text":"hoe",
        "answer": 1,
        "qId":5,
        "questionReward": 1}
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"Start",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"App",
        "a2Img":"",
        "a2text":"Up",
        "answer": 1,
        "qId":6,
        "questionReward": 1}
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"1 - 1 + 2 - 3 + 1",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"0",
        "a2Img":"",
        "a2text":"-1",
        "answer": 1,
        "qId":7,
        "questionReward": 1}
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"Man are from Mars, Women from ",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"Venus",
        "a2Img":"",
        "a2text":"Moon",
        "answer": 1,
        "qId":8,
        "questionReward": 1}
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"Teenage Mutant ______ Turtles",
        "qImg":"",
        "answerType":1,
        "a1Img":"",
        "a1text":"Ninja",
        "a2Img":"",
        "a2text":"Samurai",
        "answer": 1,
        "qId":9,
        "questionReward": 1}

];


var questionsRank4 = [
    {"questionType":1,
        "qOrder": 1,
        "qText":"Oranges",
        "qImg":"",
        "answerType":2,
        "a1Img":"img/oranges.png",
        "a1text":"",
        "a2Img":"img/app.png",
        "a2text":"",
        "answer": 1,
        "qId":1,
        "questionReward": 2
    }
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"The Taj Mahal",
        "qImg":"",
        "answerType":2,
        "a1Img":"img/acropolis.png",
        "a1text":"",
        "a2Img":"img/tajmahal.png",
        "a2text":"",
        "answer": 2,
        "qId":2,
        "questionReward": 2

    }
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"The Big Ben",
        "qImg":"",
        "answerType":2,
        "a1Img":"img/bigben.png",
        "a1text":"",
        "a2Img":"img/stonehedge.png",
        "a2text":"",
        "answer": 2,
        "qId":2,
        "questionReward": 2
    }
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"Which is in Europe?",
        "qImg":"",
        "answerType":2,
        "a1Img":"img/flags/ar.png",
        "a1text":"",
        "a2Img":"img/es.png",
        "a2text":"",
        "answer": 2,
        "qId":2,
        "questionReward": 2
    }
    ,
    {"questionType":1,
        "qOrder": 1,
        "qText":"They love curry",
        "qImg":"",
        "answerType":2,
        "a1Img":"img/flags/in.png",
        "a1text":"",
        "a2Img":"img/ie.png",
        "a2text":"",
        "answer": 2,
        "qId":2,
        "questionReward": 2
    }
];